In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv('filtered.csv')

C:\Users\dhaya\AppData\Local\Temp\ipykernel_25356\1625532197.py:3: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('filtered.csv')

In [2]:
if 'winner' in df.columns:
    df['win'] = (df['batting_team'] == df['winner']).astype(int)

In [16]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()


# Encode the 'batting_team' column
encoded_batting_teams = label_encoder.fit_transform(df['batting_team'])

# Add the encoded values as a new column
df['batting_team_encoding'] = encoded_batting_teams

# Display the encoding mapping
batting_team_mapping = dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)))
print('Batting Team Encoding Mapping:', batting_team_mapping)

Batting Team Encoding Mapping: {'Chennai Super Kings': 0, 'Deccan Chargers': 1, 'Delhi Capitals': 2, 'Delhi Daredevils': 3, 'Gujarat Lions': 4, 'Gujarat Titans': 5, 'Kings XI Punjab': 6, 'Kochi Tuskers Kerala': 7, 'Kolkata Knight Riders': 8, 'Lucknow Super Giants': 9, 'Mumbai Indians': 10, 'Pune Warriors': 11, 'Punjab Kings': 12, 'Rajasthan Royals': 13, 'Rising Pune Supergiant': 14, 'Rising Pune Supergiants': 15, 'Royal Challengers Bangalore': 16, 'Royal Challengers Bengaluru': 17, 'Sunrisers Hyderabad': 18}

In [18]:
df

,inning,Cumulative Score,Cumulative Wickets,Current Run Rate,Required Run Rate,batting_team,bowling_team,venue_canonical,winner,win,batting_team_encoding
0,1,1,0,1.000000,11.1,Kolkata Knight Riders,Royal Challengers Bangalore,M Chinnaswamy Stadium,Kolkata Knight Riders,1,8
1,1,1,0,6.000000,11.19327731092437,Kolkata Knight Riders,Royal Challengers Bangalore,M Chinnaswamy Stadium,Kolkata Knight Riders,1,8
2,1,2,0,6.000000,11.23728813559322,Kolkata Knight Riders,Royal Challengers Bangalore,M Chinnaswamy Stadium,Kolkata Knight Riders,1,8
3,1,2,0,4.000000,11.333333333333334,Kolkata Knight Riders,Royal Challengers Bangalore,M Chinnaswamy Stadium,Kolkata Knight Riders,1,8
4,1,2,0,3.000000,11.431034482758621,Kolkata Knight Riders,Royal Challengers Bangalore,M Chinnaswamy Stadium,Kolkata Knight Riders,1,8
...,...,...,...,...,...,...,...,...,...,...,...
260915,2,110,2,11.379310,0.3870967741935484,Kolkata Knight Riders,Sunrisers Hyderabad,"MA Chidambaram Stadium, Chepauk",Kolkata Knight Riders,1,8
260916,2,111,2,11.288136,0.29508196721311475,Kolkata Knight Riders,Sunrisers Hyderabad,"MA Chidambaram Stadium, Chepauk",Kolkata Knight Riders,1,8
260917,2,112,2,11.200000,0.2,Kolkata Knight Riders,Sunrisers Hyderabad,"MA Chidambaram Stadium, Chepauk",Kolkata Knight Riders,1,8
260918,2,113,2,11.114754,0.10169491525423728,Kolkata Knight Riders,Sunrisers Hyderabad,"MA Chidambaram Stadium, Chepauk",Kolkata Knight Riders,1,8
260919,2,114,2,11.032258,0.0,Kolkata Knight Riders,Sunrisers Hyderabad,"MA Chidambaram Stadium, Chepauk",Kolkata Knight Riders,1,8

In [20]:
encoded_bowling_teams = label_encoder.fit_transform(df['bowling_team'])
df['bowling_team_encoding'] = encoded_bowling_teams

In [22]:
df

,inning,Cumulative Score,Cumulative Wickets,Current Run Rate,Required Run Rate,batting_team,bowling_team,venue_canonical,winner,win,batting_team_encoding,bowling_team_encoding
0,1,1,0,1.000000,11.1,Kolkata Knight Riders,Royal Challengers Bangalore,M Chinnaswamy Stadium,Kolkata Knight Riders,1,8,16
1,1,1,0,6.000000,11.19327731092437,Kolkata Knight Riders,Royal Challengers Bangalore,M Chinnaswamy Stadium,Kolkata Knight Riders,1,8,16
2,1,2,0,6.000000,11.23728813559322,Kolkata Knight Riders,Royal Challengers Bangalore,M Chinnaswamy Stadium,Kolkata Knight Riders,1,8,16
3,1,2,0,4.000000,11.333333333333334,Kolkata Knight Riders,Royal Challengers Bangalore,M Chinnaswamy Stadium,Kolkata Knight Riders,1,8,16
4,1,2,0,3.000000,11.431034482758621,Kolkata Knight Riders,Royal Challengers Bangalore,M Chinnaswamy Stadium,Kolkata Knight Riders,1,8,16
...,...,...,...,...,...,...,...,...,...,...,...,...
260915,2,110,2,11.379310,0.3870967741935484,Kolkata Knight Riders,Sunrisers Hyderabad,"MA Chidambaram Stadium, Chepauk",Kolkata Knight Riders,1,8,18
260916,2,111,2,11.288136,0.29508196721311475,Kolkata Knight Riders,Sunrisers Hyderabad,"MA Chidambaram Stadium, Chepauk",Kolkata Knight Riders,1,8,18
260917,2,112,2,11.200000,0.2,Kolkata Knight Riders,Sunrisers Hyderabad,"MA Chidambaram Stadium, Chepauk",Kolkata Knight Riders,1,8,18
260918,2,113,2,11.114754,0.10169491525423728,Kolkata Knight Riders,Sunrisers Hyderabad,"MA Chidambaram Stadium, Chepauk",Kolkata Knight Riders,1,8,18
260919,2,114,2,11.032258,0.0,Kolkata Knight Riders,Sunrisers Hyderabad,"MA Chidambaram Stadium, Chepauk",Kolkata Knight Riders,1,8,18

In [24]:
df.drop(['batting_team', 'bowling_team'], axis=1, inplace=True)
df['Required Run Rate'] = pd.to_numeric(df['Required Run Rate'], errors='coerce').fillna(0)

In [26]:
categorical_columns = df.select_dtypes(include=['object']).columns
for column in categorical_columns:
    df[column] = label_encoder.fit_transform(df[column])

In [34]:

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score


label_encoder = LabelEncoder()
y = label_encoder.fit_transform(df['winner'])

X = df.drop(['winner'], axis=1)

# Split data into training and testing sets (70-30)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Initialize and train a Random Forest Classifier
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f'Model Accuracy: {accuracy * 100:.2f}%')

Model Accuracy: 99.83%