importing libraries

In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder #for encoding
from sklearn.model_selection import train_test_split #for training and testing

reading merged dataset

In [3]:
merged=pd.read_csv(r"merged_dataset.csv",low_memory=False)
merged

,match_id,inning,batting_team,bowling_team,over,ball,total_runs,is_wicket,cumulative runs,cumumulative wickets,...,date,venue,home_team,away_team,toss_winner,toss_decision,winner,result,result_margin,away_teeam
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,1,0,1,0,...,2008-04-18,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,Kolkata Knight Riders
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,0,0,1,0,...,2008-04-18,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,Kolkata Knight Riders
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,1,0,2,0,...,2008-04-18,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,Kolkata Knight Riders
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,0,0,2,0,...,2008-04-18,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,Kolkata Knight Riders
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,0,0,2,0,...,2008-04-18,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,Kolkata Knight Riders
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260915,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,1,0,110,2,...,2024-05-26,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,Kolkata Knight Riders
260916,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,1,0,111,2,...,2024-05-26,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,Kolkata Knight Riders
260917,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,1,0,112,2,...,2024-05-26,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,Kolkata Knight Riders
260918,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,1,0,113,2,...,2024-05-26,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,Kolkata Knight Riders
260919,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,1,0,114,2,...,2024-05-26,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,Kolkata Knight Riders

renaming the coulumns cumulative runs and cumulatives wickets

In [4]:
merged.rename(columns={
    'cumulative runs': 'cum_runs',
    'cumumulative wickets': 'cum_wickets'
}, inplace=True)

columns after renaming cumulative runs and cumulatives wickets

In [5]:
merged.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'total_runs', 'is_wicket', 'cum_runs', 'cum_wickets', 'over_completed',
       'current run rate', 'target', 'remaining_overs', 'required_run_rate',
       'season', 'city', 'date', 'venue', 'home_team', 'away_team',
       'toss_winner', 'toss_decision', 'winner', 'result', 'result_margin',
       'away_teeam'],
      dtype='object')

using labelencoder we are encoding the categorical values like batting team,bowling team,venue

In [6]:
label_encoder = LabelEncoder()
merged['batting_team_encoded'] = label_encoder.fit_transform(merged['batting_team'])
merged['bowling_team_encoded'] = label_encoder.fit_transform(merged['bowling_team'])
merged['venue_encoded'] = label_encoder.fit_transform(merged['venue'])

binary feature for win

In [7]:
merged['win'] = (merged['batting_team'] == merged['winner']).astype(int)

merged dataset after encoding categorical values and binary feature for win

In [8]:
merged.head()

,match_id,inning,batting_team,bowling_team,over,ball,total_runs,is_wicket,cum_runs,cum_wickets,...,toss_winner,toss_decision,winner,result,result_margin,away_teeam,batting_team_encoded,bowling_team_encoded,venue_encoded,win
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,1,0,1,0,...,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,Kolkata Knight Riders,5,13,23,1
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,0,0,1,0,...,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,Kolkata Knight Riders,5,13,23,1
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,1,0,2,0,...,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,Kolkata Knight Riders,5,13,23,1
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,0,0,2,0,...,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,Kolkata Knight Riders,5,13,23,1
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,0,0,2,0,...,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,Kolkata Knight Riders,5,13,23,1

only these columns for final dataframe

In [9]:
final_df = merged[['inning', 'cum_runs', 'cum_wickets', 'batting_team_encoded', 
               'bowling_team_encoded', 'venue_encoded', 'win']]
final_df.to_csv('final_dataframe.csv', index=False)

In [10]:
final_df.columns

Index(['inning', 'cum_runs', 'cum_wickets', 'batting_team_encoded',
       'bowling_team_encoded', 'venue_encoded', 'win'],
      dtype='object')

In [11]:
X = final_df.drop('win', axis=1)
Y = final_df['win']
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)
print("traning and testing done successfully")

traning and testing done successfully

In [12]:
print(f"training set size: {X_train.shape}, test set size: {X_test.shape}")

training set size: (208736, 6), test set size: (52184, 6)