In [31]:
import pandas as pd
import numpy as np

In [32]:
file_path = "matches.csv"
df = pd.read_csv(file_path)

In [33]:
df.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [34]:
df.describe()

                 id  result_margin  target_runs  target_overs
count  1.095000e+03    1076.000000  1092.000000   1092.000000
mean   9.048283e+05      17.259294   165.684066     19.759341
std    3.677402e+05      21.787444    33.427048      1.581108
min    3.359820e+05       1.000000    43.000000      5.000000
25%    5.483315e+05       6.000000   146.000000     20.000000
50%    9.809610e+05       8.000000   166.000000     20.000000
75%    1.254062e+06      20.000000   187.000000     20.000000
max    1.426312e+06     146.000000   288.000000     20.000000

In [35]:
df = df.drop(columns=['method','player_of_match','match_type','date','venue','umpire1','umpire2'])

In [36]:
df.head()

,id,season,city,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over
0,335982,2007/08,Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N
1,335983,2007/08,Chandigarh,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N
2,335984,2007/08,Delhi,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N
3,335985,2007/08,Mumbai,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N
4,335986,2007/08,Kolkata,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N

In [37]:
# Check for null values in each column
null_values = df.isnull().sum()

print("Columns with Null Values:")
print(null_values[null_values > 0])

# Display total missing values
total_missing = df.isnull().sum().sum()
print(f"\nTotal Missing Values in Dataset: {total_missing}")

Columns with Null Values:
city             51
winner            5
result_margin    19
target_runs       3
target_overs      3
dtype: int64

Total Missing Values in Dataset: 81

In [38]:
# Handling missing values

if "winner" in df.columns:
    df["winner"].fillna("Unknown", inplace=True)

if "result_margin" in df.columns:
    df["result_margin"].fillna(0, inplace=True)

if "target_runs" in df.columns:
    df["target_runs"].fillna(0, inplace=True)

if "target_overs" in df.columns:
    df["target_overs"].fillna(0, inplace=True)

#Fill any other numerical columns with median values
num_cols = df.select_dtypes(include=["number"]).columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())

#Check if all missing values are handled
print("Missing values after handling:\n", df.isnull().sum())

#Save the cleaned dataset (optional)
df.to_csv("deliveries_cleaned.csv", index=False)

print("\nMissing values successfully replaced with meaningful values!")

Missing values after handling:
 id                0
season            0
city             51
team1             0
team2             0
toss_winner       0
toss_decision     0
winner            0
result            0
result_margin     0
target_runs       0
target_overs      0
super_over        0
dtype: int64

Missing values successfully replaced with meaningful values!

<ipython-input-38-e412f1afbc30>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["winner"].fillna("Unknown", inplace=True)
<ipython-input-38-e412f1afbc30>:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["result_margin"].fillna(0, inplace=True)
<ipython-input-38-e412f1afbc30>:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["target_runs"].fillna(0, inplace=True)
<ipython-input-38-e412f1afbc30>:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["target_overs"].fillna(0, inplace=True)

In [43]:
matches = pd.read_csv('matches.csv')
deliveries = pd.read_csv('deliveries.csv')

matches.fillna({'winner': 'No Result', 'result_margin': 0, 'toss_winner': 'Unknown'}, inplace=True)
deliveries.fillna(0, inplace=True)

merged_data = pd.merge(deliveries, matches, left_on='match_id', right_on='id', how='inner')

columns_to_keep = ['match_id','date','city', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner', 'result',
                   'result_margin', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
                   'total_runs', 'is_wicket']
merged_data = merged_data[columns_to_keep]

merged_data.rename(columns={'team1': 'home', 'team2': 'away'}, inplace=True)

# Standardize team names
team_name_mapping = {
    'Delhi Daredevils': 'Delhi Capitals',
    'Royal Challengers Bangalore': 'Royal Challengers Bengaluru',
    'Rising Pune Supergiant': 'Rising Pune Supergiants',
    "Kings XI Punjab": "Punjab Kings"
}
merged_data['home'] = merged_data['home'].replace(team_name_mapping)
merged_data['away'] = merged_data['away'].replace(team_name_mapping)
merged_data['batting_team'] = merged_data['batting_team'].replace(team_name_mapping)
merged_data['bowling_team'] = merged_data['bowling_team'].replace(team_name_mapping)
merged_data['toss_winner'] = merged_data['toss_winner'].replace(team_name_mapping)
merged_data['winner'] = merged_data['winner'].replace(team_name_mapping)

#new features
merged_data['overs_completed'] = merged_data['over'] + merged_data['ball'] / 6
merged_data['cumulative_runs'] = merged_data.groupby(['match_id', 'inning'])['total_runs'].cumsum()
merged_data['cumulative_wickets'] = merged_data.groupby(['match_id', 'inning'])['is_wicket'].cumsum()
merged_data['current_run_rate'] = merged_data['cumulative_runs'] / merged_data['overs_completed']

#required run rate
target_score = merged_data.groupby('match_id')['cumulative_runs'].transform('max')
remaining_runs = target_score - merged_data['cumulative_runs']
remaining_overs = 20 - merged_data['overs_completed']
merged_data['required_run_rate'] = remaining_runs / remaining_overs

In [40]:
merged_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260920 entries, 0 to 260919
Data columns (total 22 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   match_id            260920 non-null  int64
 1   date                260920 non-null  object
 2   city                248523 non-null  object
 3   home                260920 non-null  object
 4   away                260920 non-null  object
 5   toss_winner         260920 non-null  object
 6   toss_decision       260920 non-null  object
 7   winner              260920 non-null  object
 8   result              260920 non-null  object
 9   result_margin       260920 non-null  float64
 10  inning              260920 non-null  int64
 11  batting_team        260920 non-null  object
 12  bowling_team        260920 non-null  object
 13  over                260920 non-null  int64
 14  ball                260920 non-null  int64
 15  total_runs          260920 non-null  int64
 16  is_wicket           260920 non-null  int64
 17  overs_completed     260920 non-null  float64
 18  cumulative_runs     260920 non-null  int64
 19  cumulative_wickets  260920 non-null  int64
 20  current_run_rate    260920 non-null  float64
 21  required_run_rate   260492 non-null  float64
dtypes: float64(4), int64(8), object(10)
memory usage: 43.8+ MB

In [41]:
from sklearn.preprocessing import LabelEncoder
# Convert 'date' to datetime
merged_data['date'] = pd.to_datetime(merged_data['date'])

# Encode categorical columns using Label Encoding
label_encoder = LabelEncoder()
categorical_columns = merged_data.select_dtypes(include=['string']).columns
for column in categorical_columns:
    merged_data[column] = label_encoder.fit_transform(merged_data[column])

# Display the processed data types
print(merged_data.dtypes)

match_id                       int64
date                  datetime64[ns]
city                          object
home                          object
away                          object
toss_winner                   object
toss_decision                 object
winner                        object
result                        object
result_margin                float64
inning                         int64
batting_team                  object
bowling_team                  object
over                           int64
ball                           int64
total_runs                     int64
is_wicket                      int64
overs_completed              float64
cumulative_runs                int64
cumulative_wickets             int64
current_run_rate             float64
required_run_rate            float64
dtype: object

In [42]:
print(merged_data.head())

   match_id       date       city                         home  \
0    335982 2008-04-18  Bangalore  Royal Challengers Bengaluru
1    335982 2008-04-18  Bangalore  Royal Challengers Bengaluru
2    335982 2008-04-18  Bangalore  Royal Challengers Bengaluru
3    335982 2008-04-18  Bangalore  Royal Challengers Bengaluru
4    335982 2008-04-18  Bangalore  Royal Challengers Bengaluru

                    away                  toss_winner toss_decision  \
0  Kolkata Knight Riders  Royal Challengers Bengaluru         field
1  Kolkata Knight Riders  Royal Challengers Bengaluru         field
2  Kolkata Knight Riders  Royal Challengers Bengaluru         field
3  Kolkata Knight Riders  Royal Challengers Bengaluru         field
4  Kolkata Knight Riders  Royal Challengers Bengaluru         field

                  winner result  result_margin  ...  \
0  Kolkata Knight Riders   runs          140.0  ...
1  Kolkata Knight Riders   runs          140.0  ...
2  Kolkata Knight Riders   runs          140.0  ...
3  Kolkata Knight Riders   runs          140.0  ...
4  Kolkata Knight Riders   runs          140.0  ...

                  bowling_team over ball  total_runs  is_wicket  \
0  Royal Challengers Bengaluru    0    1           1          0
1  Royal Challengers Bengaluru    0    2           0          0
2  Royal Challengers Bengaluru    0    3           1          0
3  Royal Challengers Bengaluru    0    4           0          0
4  Royal Challengers Bengaluru    0    5           0          0

   overs_completed  cumulative_runs  cumulative_wickets  current_run_rate  \
0         0.166667                1                   0               6.0
1         0.333333                1                   0               3.0
2         0.500000                2                   0               4.0
3         0.666667                2                   0               3.0
4         0.833333                2                   0               2.4

   required_run_rate
0          11.142857
1          11.237288
2          11.282051
3          11.379310
4          11.478261

[5 rows x 22 columns]